name: 설정 작업 (Setting)
description: 환경/구성(Settings) 변경 작업을 위한 템플릿
title: "[Setting]: "
labels: ["setting"]
body:
  - type: input
    id: branch_keyword
    attributes:
      label: "Branch Keyword"
      description: "영문 소문자로 간결한 브랜치 명을 입력하세요 (예: employee, login-modal)"
    validations:
      required: true

  - type: input
    id: setting_title
    attributes:
      label: "설정 제목"
      description: "이번에 무엇을 세팅/변경하나요?"
      placeholder: "프로덕션 환경 변수 정리"
    validations:
      required: true

  - type: textarea
    id: setting_summary
    attributes:
      label: "설정 내용(간단히)"
      description: "무엇을, 왜, 어디에 세팅할지 짧게 적어주세요."
      placeholder: |
        - 대상: prod / dev
        - 항목: SPRING_PROFILES_ACTIVE, LOG_LEVEL, CORS 도메인
        - 목적: 배포 전 환경 정합성 확보
    validations:
      required: true