name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Gradle 캐싱
        uses: gradle/actions/setup-gradle@v3

      - name: 빌드 권한 부여
        run: chmod +x ./gradlew

      - name: 테스트 돌리기
        run: ./gradlew clean test

      - name: 테스트 결과 보고서 업로드
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            ./build/reports/tests/
            ./build/reports/jacoco/
            ./build/reports/problems/
          retention-days: 7
          include-hidden-files: true